name: arboon
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+8

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  buildcondition: ^0.0.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  sizer: ^2.0.15
  lottie: ^1.3.0
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.9.3
  easy_localization: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0
  country_code_picker: ^2.0.2
  flutter_svg: ^1.1.1+1
  flutter_zoom_drawer: ^3.0.2
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.8
  geocoding: ^2.0.4
  searchfield: ^0.6.6
  url_launcher: ^6.1.5
  webviewx: ^0.2.1
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  scan: ^1.6.0
  connectivity_plus: ^2.3.6
  time_range_picker: ^2.2.0
  file_picker: ^5.1.0
  pdf_viewer_plugin: ^2.0.1
 

 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_launcher.png"


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - lang/

 
  fonts:
    - family: Iconly-Broken
      fonts:
        - asset: assets/fonts/icons.ttf
